server:
  port: 8080
  address: 0.0.0.0
spring:
  application: ElectricVehicleSystem
  datasource:
    url: jdbc:mysql://localhost:3306/test
#    url: jdbc:mysql://103.90.226.19/emob
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true
  main:
    allow-circular-auto: true
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: cn100705@gmail.com
    password: kiyk opth gbpu agre
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #            connectiontimeout: 5000
  #            timeout: 5000
  #            writetimeout: 5000
  #            socketFactory:
  #              port: 587
  #              class: javax.net.ssl.SSLSocketFactory
  #              fallback: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  security:
    public-apis:
      - /swagger-ui/**
      - /v3/api-docs/**
      - /swagger-resources/**
      - /api/auth/login
      - /api/auth/register
      - /websocket/**
  #Redis
  data:
    redis:
      host: localhost
      port: 6379
      password: 12345678
      database: 0
  #JWT
  jwt:
    secretkey: yxzHhwvD3gfwENyU95c1VUb2iH5manykVOuPwj1WTy4=
    duration: 30
  ai:
    openai:
      api-key: 
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
#firebase-admin
fcm:
  credentials:
    file:
      path: ./firebase-admin.json
#logging:
#  level:
#    org:
#      springframework: security=DEBUG
